import React from "react";
import { Helmet } from "react-helmet";

import BaseLayout from "components/layout/BaseLayout";
import { Hero } from "components/hero/Hero";
import { Link } from "components/link/Link";
import { Block } from "components/block/Block";

export default () => (
  <BaseLayout text>
    <Helmet title="Privacy Policy" />
    <Hero>
      <h1>Privacy Policy</h1>
      <p>Updated: August 25, 2020</p>
    </Hero>
    <Block>
      <h2>Google Analytics</h2>
      <p>
        This website uses Google Analytics, a web analytics service provided by
        Google, Inc. (“Google”). Google Analytics uses “cookies”, which are text
        files placed on your computer, to help the website analyze how users use
        the site. The information generated by the cookie about your use of the
        website (including your IP address) will be transmitted to and stored by
        Google on servers in the United States. Google will use this information
        for the purpose of evaluating your use of the website, compiling reports
        on website activity for website operators and providing other services
        relating to website activity and internet usage. Google may also
        transfer this information to third parties where required to do so by
        law, or where such third parties process the information on Google‘s
        behalf. Google will not associate your IP address with any other data
        held by Google. You may refuse the use of cookies by selecting the
        appropriate settings on your browser, however please note that if you do
        this you may not be able to use the full functionality of this website.
        By using this website, you consent to the processing of data about you
        by Google in the manner and for the purposes set out above.
      </p>
      <h2>Database</h2>
      <p>
        All uploaded data and data at the time of account creation are saved on
        the server. To build the database, the Dr Pepper Map Club website uses
        Google Firebase services.Through that, your data will also be handled
        under the privacy policy of{" "}
        <Link href="https://firebase.google.com/">Firebase.</Link>
      </p>
      <blockquote>
        <h2>
          <Link href="https://www.firebase.com/terms/privacy-policy.html">
            Firebase: Privacy Policy
          </Link>
        </h2>
        <h6>Effective Date: 2/10/2013</h6>
        <p>
          Firebase values your privacy. At www.firebase.com we offer a real-time
          backend-as-a-service for powering cloud apps. In this Privacy Policy
          („Policy“), we describe how we collect, use, and disclose information
          that we obtain about visitors to our website https://www.firebase.com
          (the „Site“) and the services available through our Site
          (collectively, the „Services“).
        </p>
        <p>
          By visiting the Site, or using any of our Services, you agree that
          your personal information will be handled as described in this Policy.
          Your use of our Site or Services, and any dispute over privacy, is
          subject to this Policy and our Terms of Service, available below,
          including its applicable limitations on damages and the resolution of
          disputes. The Firebase Terms of Service are incorporated by reference
          into this Policy.
        </p>
        <h6>What Information Do We Collect About You and Why?</h6>
        <p>
          We may collect information about you directly from you and from third
          parties, as well as automatically through your use of our Site or
          Services.
        </p>
        <h6>Information We Collect Directly From You</h6>
        <p>
          Certain areas and features of our Site and Services may require
          registration. To register you must provide your email address and a
          password. We also may collect additional optional information from
          you, including your name, location, and phone number; however, you are
          not required to provide us with this information. In addition, if you
          make a purchase, we will also request that you provide your credit or
          debit card information and your billing address.
        </p>
        <p>
          We may use this information in aggregated form or we may associate it
          with your username and other personal information that we collect
          about you.
        </p>
        <h6>
          Information that We Collect About You from Social Networking Sites
        </h6>
        <p>
          You also may log into our Site and Application through GitHub. By
          logging in through GitHub you are granting us access to your email
          address. We store the information that we receive from GitHub with
          other information that we collect from you or receive about you.
        </p>
        <h6>Information We Collect Automatically</h6>
        <p>
          We may automatically collect the following information about your use
          of our Site or Services through cookies, web beacons, and other
          technologies: your domain name; your browser type and operating
          system; web pages you view; links you click; your IP address; the
          length of time you visit our Site and or use our Services; and the
          referring URL, or the webpage that led you to our Site, and the
          following: access time, browser type, domain name, IP address, page
          views and referring URL. Please see the section „What About Cookies
          and Other Tracking Mechanisms?“ below for more information about our
          use of cookies and other tracking mechanisms.
        </p>
        <h6>How We Use Your Information</h6>
        <p>
          We use the information that we gather about you for the following
          purposes:
        </p>
        <p>
          To provide our Services to you, to communicate with you about your use
          of our Services, to respond to your inquiries, to fulfill your orders,
          and for other customer service purposes. To tailor the content and
          information that we may send or display to you, to offer location
          customization, and personalized help and instructions, and to
          otherwise personalize your experiences while using the Site or our
          Services. For marketing and promotional purposes. For example, we may
          use your information, such as your email address, to send you news and
          newsletters, special offers, and promotions, or to otherwise contact
          you about products or information we think may interest you. We also
          may use the information that we learn about you to assist us in
          advertising our Services on third party websites. To better understand
          how users access and use our Site and Services, both on an aggregated
          and individualized basis, in order to improve our Site and Services
          and respond to user desires and preferences, and for other research
          and analytical purposes.
        </p>
        <h6>How We Share Your Information</h6>
        <p>
          We may share the information that we collect about you, including
          personally identifiable information, as follows:
        </p>
        <p>
          Affiliates We may disclose the information we collect from you to our
          affiliates or subsidiaries; however, if we do so, their use and
          disclosure of your personally identifiable information will be subject
          to this Policy. Service Providers. We may disclose the information we
          collect from you to third party vendors, service providers,
          contractors or agents who perform functions on our behalf. Business
          Transfers If we are acquired by or merged with another company, if
          substantially all of our assets are transferred to another company, or
          as part of a bankruptcy proceeding, we may transfer the information we
          have collected from you to the other company. In Response to Legal
          Process We also may disclose the information we collect from you in
          order to comply with the law, a judicial proceeding, court order, or
          other legal process, such as in response to a court order or a
          subpoena. To Protect Us and Others We also may disclose the
          information we collect from you where we believe it is necessary to
          investigate, prevent, or take action regarding illegal activities,
          suspected fraud, situations involving potential threats to the safety
          of any person, violations of our Terms of Use or this Policy, or as
          evidence in litigation in which Firebase is involved. Aggregate and
          De-Identified Information We may share aggregate or de-identified
          information about users with third parties for marketing, advertising,
          research or similar purposes.
        </p>
        <h6>Our Use of Cookies and Other Tracking Mechanisms</h6>
        <p>
          We use cookies and other tracking mechanisms to track information
          about your use of our Site or Services. We may combine this
          information with other personal information we collect from you.
          Cookies are alphanumeric identifiers that we transfer to your
          computer‘s hard drive through your web browser for record-keeping
          purposes. Some cookies allow us to make it easier for you to navigate
          our Site and Services, while others are used to enable a faster log-in
          process or to allow us to track your activities at our Site and
          Service. There are two types of cookies: session and persistent
          cookies.
        </p>
        <p>
          Session Cookies Session cookies exist only during an online session.
          They disappear from your computer when you close your browser or turn
          off your computer. We use session cookies to allow our systems to
          uniquely identify you during a session or while you are logged into
          the Site. This allows us to process your online transactions and
          requests and verify your identity, after you have logged in, as you
          move through our Site. Persistent cookies Persistent cookies remain on
          your computer after you have closed your browser or turned off your
          computer. We use persistent cookies to track aggregate and statistical
          information about user activity.
        </p>
        <h6>Third Party Cookies</h6>
        <p>
          We may also engage third parties to track and analyze Site data. We
          use the data collected by such third parties to help us administer and
          improve the quality of the Site and to analyze Site usage. Such third
          parties may combine the information that we provide about you with
          other information that they have collected. This Policy does not cover
          such third parties‘ use of the data.
        </p>
        <h6>Disabling Cookies</h6>
        <p>
          Most web browsers automatically accept cookies, but if you prefer, you
          can edit your browser options to block them in the future. The Help
          portion of the toolbar on most browsers will tell you how to prevent
          your computer from accepting new cookies, how to have the browser
          notify you when you receive a new cookie, or how to disable cookies
          altogether. Visitors to our Site who disable cookies will be able to
          browse certain areas of the Site, but some features may not function.
        </p>
        <h6>Third Party Analytics</h6>
        <p>
          We use automated devices and applications, such as Google Analytics,
          to evaluate usage of our Site. We also may use other analytic means to
          evaluate our Services. We use these tools to help us improve our
          Services, performance and user experiences. We do not share your
          personal information with these third parties.
        </p>
        <h6>Third-Party Links</h6>
        <p>
          Our Site and Services may contain links to third-party websites. Any
          access to and use of such linked websites is not governed by this
          Policy, but instead is governed by the privacy policies of those third
          party websites. We are not responsible for the information practices
          of such third party websites.
        </p>
        <h6>Security of My Personal Information</h6>
        <p>
          We have implemented commercially reasonable precautions, including,
          where appropriate, password protection, encryption, SSL, firewalls,
          and internal restrictions on who may access data to protect the
          information we collect from loss, misuse, and unauthorized access,
          disclosure, alteration, and destruction. Please be aware that despite
          our best efforts, no data security measures can guarantee 100%
          security.
        </p>
        <p>
          You should take steps to protect against unauthorized access to your
          password, phone, and computer by, among other things, signing off
          after using a shared computer, choosing a robust password that nobody
          else knows or can easily guess, and keeping your log-in and password
          private. We are not responsible for any lost, stolen, or compromised
          passwords or for any activity on your account via unauthorized
          password activity.
        </p>
        <h6>Access To My Personal Information</h6>
        <p>
          You may modify personal information that you have submitted by logging
          into your account and updating your profile information. Please note
          that copies of information that you have updated, modified or deleted
          may remain viewable in cached and archived pages of the Site for a
          period of time.
        </p>
        <h6>
          What Choices Do I Have Regarding Use of My Personal Information?
        </h6>
        <p>
          We may send periodic promotional or informational emails to you. You
          may opt-out of such communications by following the opt-out
          instructions contained in the e-mail. Please note that it may take up
          to 10 business days for us to process opt-out requests. If you opt-out
          of receiving emails about recommendations or other information we
          think may interest you, we may still send you e-mails about your
          account or any Services you have requested or received from us.
        </p>
        <h6>Children Under 13</h6>
        <p>
          Our Services are not designed for children under 13. If we discover
          that a child under 13 has provided us with personal information, we
          will delete such information from our systems.
        </p>
        <h6>Contact Us</h6>
        <p>
          If you have questions about the privacy aspects of our Services or
          would like to make a complaint, please contact us at
          firebase-support@google.com.
        </p>
        <h6>Changes to this Policy</h6>
        <p>
          This Policy is current as of the Effective Date set forth above. We
          may change this Policy from time to time, so please be sure to check
          back periodically. We will post any changes to this Policy on our
          Site, at www.firebase.com. If we make any changes to this Policy that
          materially affect our practices with regard to the personal
          information we have previously collected from you, we will endeavor to
          provide you with notice in advance of such change by highlighting the
          change on our Site.
        </p>
      </blockquote>
    </Block>
  </BaseLayout>
);
